function config = zoom_config()
% ZOOM_CONFIG  Central configuration for beamforming experiments and UI batch runs.
%
% Pipeline:
%   1) Load microphone positions (XML) and multichannel audio (HDF5 or WAV).
%   2) process_beamforming() loops beamformers x focus points.
%   3) Each beamformer entry is dispatched through beamformer_dispatch.m
%      to the implementation files in /beamformer.
%
% Beamformer list (config.beamformers):
%   Each cell is a struct:
%     .name   - Human-readable label (used in logs, filenames, and UI).
%     .core   - MATLAB function name under /beamformer (must be on path).
%     .params - Optional struct of algorithm-specific options.
%               Keys are consumed by beamformer_dispatch.m.
%               Add / remove fields here to tune a method without changing
%               the number of positional arguments the core function takes.
%
% Focus points (config.points):
%   Struct array with .name [string] and .position [x, y, z] (m).
%
% To add a new beamformer:
%   1) Create the MATLAB function in /beamformer with the standard signature
%      (see BEAMFORMER_DEVELOPER_GUIDE.md).
%   2) Add an entry to config.beamformers below.
%   3) Add a dispatch case in processing/beamformer_dispatch.m.

    config = struct();

    % --- Physical medium -------------------------------------------------------
    config.z_distance = 0.6;    % reference plane distance (m)
    config.c          = 343;    % speed of sound (m/s)

    % --- Input / output paths --------------------------------------------------
    config.xml_file   = 'config/uma16_array.xml';
    config.audio_file = 'config/h5_Files/Heydar.wav';
    config.output_dir = 'output';

    % --- Registered beamformers (execution order) ------------------------------
    config.beamformers = {
        struct( ...
            'name',   'CGMM_MVDR', ...
            'core',   'CGMM_MVDR_Zoom', ...
            'params', struct() ...
        )
        struct( ...
            'name',   'Base_Time', ...
            'core',   'Base_BeamForming_Time_Domain', ...
            'params', struct() ...
        )
%         struct( ...
%             'name',   'Base_Freq', ...
%             'core',   'Base_Beamforming_Freq_Domain', ...
%             'params', struct() ...
%         )
        struct( ...
            'name',   'MVDR_Time', ...
            'core',   'MVDR_Zoom_Time_Domain', ...
            'params', struct() ...
        )
%         struct( ...
%             'name',   'MVDR_Freq', ...
%             'core',   'MVDR_Zoom_Freq_Domain', ...
%             'params', struct('shift_range', 11500:100:12500) ...
%         )
        struct( ...
            'name',   'LCMV_Spatial_Time', ...
            'core',   'LCMV_Spatial_Time_Domain', ...
            'params', struct() ...
        )
        struct( ...
            'name',   'LCMV_GSC', ...
            'core',   'LCMV_GSC_Zoom', ...
            'params', struct() ...
        )
    };

    % --- Focus grid (9 points matching lcmv_gsc_analysis.py) ------------------
    z = config.z_distance;
    config.points = struct( ...
        'name', { ...
            'Center', ...
            'Top-Right', ...
            'Bottom-Right', ...
            'Top-Left', ...
            'Bottom-Left', ...
            'Top-Center', ...
            'Bottom-Center', ...
            'Right-Center', ...
            'Left-Center' ...
        }, ...
        'position', { ...
            [ 0.0,  0.0, z], ...
            [ 0.2,  0.2, z], ...
            [ 0.2, -0.2, z], ...
            [-0.2,  0.2, z], ...
            [-0.2, -0.2, z], ...
            [ 0.0,  0.2, z], ...
            [ 0.0, -0.2, z], ...
            [ 0.2,  0.0, z], ...
            [-0.2,  0.0, z]  ...
        } ...
    );
%     config.points = struct( ...
%         'name', { ...
%             'Center', ...
%             'Right-Center', ...
%         }, ...
%         'position', { ...
%             [ 0.0,  0.0, z], ...
%             [ 0.2,  0.0, z], ...
%         } ...
%     );

    % --- Energy analysis window ------------------------------------------------
    config.energy_window_ms = 100;

    % --- Ensure output directory exists ----------------------------------------
    if ~exist(config.output_dir, 'dir')
        mkdir(config.output_dir);
    end
end
